### ISSUE TITLE
Issue with list(map(lambda x: write(x, loaded_ims), output))

### ISSUE THREAD

**Issue by thanhhien1166** [PankajJ08/Real-Time-Object-Detection-using-YOLO-v3#1]
Hi there! How can I fix this when I run your code?
Traceback (most recent call last):
  File "img_detect.py", line 181, in <module>
    list(map(lambda x: write(x, loaded_ims), output))
  File "img_detect.py", line 181, in <lambda>
    list(map(lambda x: write(x, loaded_ims), output))
TypeError: 'int' object is not callable

**Comment by draxler1** [comment]
It is happening because in `img_detect.py` line 41 there is function name `write()` is defined and at line 113 there is the same name variable that is write initialized to zero.

Just change and replace either write function name to something other than write or change write variable name. It will solve your problem.

For more infomation refer this issue : https://stackoverflow.com/questions/9767391/typeerror-int-object-is-not-callable
